In [24]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras

- Koristeci biblioteku pandas ucitati datotetku fruit.csv
- Ispisati prvih pet instanci skupa podataka

In [25]:
df = pd.read_csv('fruit.csv')
df.head()

   fruit_label fruit_name  fruit_subtype  mass  width  height  color_score
0            1      apple   granny_smith   192    8.4     7.3         0.55
1            1      apple   granny_smith   180    8.0     6.8         0.59
2            1      apple   granny_smith   176    7.4     7.2         0.60
3            2   mandarin       mandarin    86    6.2     4.7         0.80
4            2   mandarin       mandarin    84    6.0     4.6         0.79

- Izdvojiti kolonu Class kao ciljnu promenljivu i kodirati je pomocu keras biblioteke

In [26]:
print(df['fruit_label'].unique())

[1 2 3 4]

In [27]:
classes = df['fruit_label']
classes_cat = keras.utils.to_categorical(classes)

- Podeliti podatke na skup za treniranje i skup za testiranje

In [28]:
df = pd.get_dummies(df, prefix='', prefix_sep='')
train_dataset = df.sample(frac=0.8, random_state=42)
test_dataset = df.drop(train_dataset.index)

In [29]:
print(train_dataset.shape)
print(test_dataset.shape)

(47, 23)
(12, 23)

In [30]:
X_train = train_dataset.drop('fruit_label', axis=1)
y_train = train_dataset['fruit_label']

X_test = test_dataset.drop('fruit_label', axis=1)
y_test = test_dataset['fruit_label']

- Standardizovati podatke

In [31]:
X_train

,mass,width,height,color_score,apple,lemon,mandarin,mandarin,orange,granny_smith,...,golden_delicious,granny_smith,mandarin,mandarin,selected_seconds,spanish_belsan,spanish_jumbo,turkey_navel,unknown,urkey_navel
0,192,8.4,7.3,0.55,True,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
5,80,5.8,4.3,0.77,False,False,False,True,False,False,...,False,False,True,False,False,False,False,False,False,False
34,142,7.6,7.8,0.75,False,False,False,False,True,False,...,False,False,False,False,False,False,False,True,False,False
13,164,7.3,7.7,0.70,True,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
45,186,7.2,9.2,0.72,False,True,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
53,120,6.0,8.4,0.74,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
57,152,6.5,8.5,0.72,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
25,356,9.2,9.2,0.75,False,False,False,False,True,False,...,False,False,False,False,False,False,True,False,False,False
47,196,7.3,9.7,0.72,False,True,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
12,154,7.0,7.1,0.88,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
49,132,5.8,8.7,0.73,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
3,86,6.2,4.7,0.80,False,False,True,False,False,False,...,False,False,True,False,False,False,False,False,False,False
36,160,7.1,7.6,0.76,False,False,False,False,True,False,...,False,False,False,False,False,False,False,True,False,False
31,210,7.8,8.0,0.82,False,False,False,False,True,False,...,False,False,False,False,True,False,False,False,False,False
8,178,7.1,7.8,0.92,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
17,168,7.5,7.6,0.73,True,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
6,80,5.9,4.3,0.81,False,False,False,True,False,False,...,False,False,False,True,False,False,False,False,False,False
4,84,6.0,4.6,0.79,False,False,True,False,False,False,...,False,False,True,False,False,False,False,False,False,False
54,116,6.1,8.5,0.71,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
19,162,7.4,7.2,0.85,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
30,158,7.1,7.5,0.79,False,False,False,False,True,False,...,False,False,False,False,True,False,False,False,False,False
50,130,6.0,8.2,0.71,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
44,200,7.3,10.5,0.72,False,True,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
55,116,6.3,7.7,0.72,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
15,156,7.7,7.1,0.69,True,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
9,172,7.4,7.0,0.89,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
27,204,7.5,9.2,0.77,False,False,False,False,True,False,...,False,False,False,False,True,False,False,False,False,False
26,362,9.6,9.2,0.74,False,False,False,False,True,False,...,False,False,False,False,False,False,True,False,False,False
16,156,7.6,7.5,0.67,True,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
24,342,9.0,9.4,0.75,False,False,False,False,True,False,...,False,False,False,False,False,False,True,False,False,False
33,190,7.5,8.1,0.74,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,True
56,116,5.9,8.1,0.73,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
41,180,7.6,8.2,0.79,False,False,False,False,True,False,...,False,False,False,False,False,False,False,True,False,False
11,172,7.1,7.6,0.92,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
32,164,7.2,7.0,0.80,False,False,False,False,True,False,...,False,False,False,False,True,False,False,False,False,False
52,118,5.9,8.0,0.72,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
40,154,7.1,7.5,0.78,False,False,False,False,True,False,...,False,False,False,False,False,False,False,True,False,False
37,154,7.3,7.3,0.79,False,False,False,False,True,False,...,False,False,False,False,False,False,False,True,False,False
29,160,7.0,7.4,0.81,False,False,False,False,True,False,...,False,False,False,False,True,False,False,False,False,False
43,194,7.2,10.3,0.70,False,True,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
1,180,8.0,6.8,0.59,True,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
21,156,7.4,7.4,0.84,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,176,7.4,7.2,0.60,True,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
46,216,7.3,10.2,0.71,False,True,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
39,144,6.8,7.4,0.75,False,False,False,False,True,False,...,False,False,False,False,False,False,False,True,False,False
35,150,7.1,7.9,0.75,False,False,False,False,True,False,...,False,False,False,False,False,False,False,True,False,False
23,170,7.6,7.9,0.88,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [32]:
from sklearn.preprocessing import StandardScaler

In [33]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [34]:
print(len(X_train[0]))
print(len(y_train.unique()))

22
4

In [35]:
model = keras.models.Sequential()
model.add(keras.layers.Dense(len(X_train[0]), activation='relu'))
model.add(keras.layers.Dense(32, activation='relu'))
model.add(keras.layers.Dense(10, activation='relu'))
model.add(keras.layers.Dense(y_train.unique(), activation='softmax'))

In [38]:
print(type(X_train))
print(type(y_train))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

In [36]:
y_train = keras.utils.to_categorical(y_train.values)
y_test = keras.utils.to_categorical(y_test.values)
print(type(y_train))

<class 'numpy.ndarray'>

In [37]:
learning_rates = [0.001, 0.01, 0.1]
best_lr = 0
best_acc = -1.0
best_history = None

for lr in learning_rates:
    model.compile(optimizer=keras.optimizers.Adam(learning_rate=lr), loss=keras.losses.CategoricalCrossentropy(), metrics=['accuracy'])
    history = model.fit(X_train, y_train, epochs = 30)
    _, acc = model.evaluate(X_test, y_test, verbose=0)
    if acc > best_acc:
        best_acc = acc
        best_lr = lr
        best_history = history

print(f'Najbolji learning rate je {best_lr}')

Epoch 1/30

ValueError: Invalid dtype: ndarray